import React, { useState } from "react"
import Head from "next/head"
import styles from "../styles/Home.module.css"
import AddListForm from "../components/AddListForm"
import Lists from "../components/Lists"

export default function HomePage() {
  const [lists, setLists] = useState([])

  const addNewList = (newList) => {
    setLists([...lists, newList])
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Todo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Next.js project</h1>
      <AddListForm addNewList={addNewList} />
      <Lists lists={lists} />
    </div>
  )
}
